# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
#figlet Down Here

echo "$(tput setaf 15)"
figlet -f Univers "Stephan"

echo "$(tput setaf 46)             The Quieter You Become,the More you are able to hear!"
echo "$(tput setaf 21)               I never had so much control before but now."
echo "$(tput setaf 9)                     I am a $(tput setaf 46) \$uperuser."
echo "$(tput setaf 12)                         yeah! U heard me!"

#my Alias down here
t=/home/tool
script=/home/script
wifi=$script/wificrack
software=/media/root/Stephanware/Softwares
apache=$script/apache2
#-------------------------------------MyScripts.sh ----------------------
alias hs="$script/hscript.sh"
alias mountall="$script/mountall.sh"
alias mall="$script/mountall.sh"
alias wifiadb="$script/adb-sh/wifiadb.sh"
alias wifi="$script/wifiwlan0mon.sh"
alias h="$script/hscript.sh"
alias venom="$script/venom.sh"
alias qrcode="$script/qrcode.sh"
alias c="$script/console.sh"
alias cmd="$script/cmd.sh"
alias path="$script/path.sh"
alias vlink="$script/vlink.sh"
alias github="$script/github.sh"
alias allcmd="$script/allcommand.sh"
alias pkg="$script/apt.sh"
#------------------------------------Open Settings ----------------------
alias hotspot="$script/hotspot.sh"
#alias gotobed="`shutdown now`"
#alias enject="enject /dev/cdrom"	
alias bye="$script/shutdown.sh"
#------------------------------------ Wifi Hacking -------------------
alias hackwifi="$wifi/hackwifi.sh"
alias wifimonitor="$wifi/wifimonitor.sh"
alias wificap="$wifi/wificapture.sh"
alias wifihshake="$wifi/wifihandshake.sh"
alias wificrack="$wifi/wificrack.sh"
alias vlc="$script/vlc.sh"
#------------------------------------ Software ------------------------
alias pycharm="$software/pycharm-community-2018.1.4/bin/pycharm.sh"
alias android="$software/android-studio/bin/studio.sh"
alias lusb="/home/tool/liveusb/unetbootin-linux64-661.bin"
#----------------------- Open Websites and Links  ---------------------------
alias color="$script/colorTEXT.sh"
alias findmydevice="$script/findmydevice.sh"
alias nbyte="$script/nullbyte.sh"
alias jiofi="$script/jiofi.sh"
alias aserver="$apache/start-server.sh"
alias wsite="$script/websites.sh"
#----------------------- Open Directories -----------------
alias wallp="$script/wallpaper.sh" 
alias videos="$script/video.sh" 
alias fshow="$script/figlet.sh"
alias allfiglet="$script/allfiglet.sh"
#------------------------- Lazy Console Shortcuts -------------------
alias ntool="$script/netool.sh"
alias cdlog="/home/cdlog/readme.sh"
alias area51="$script/restricted.sh"
#Coded by Stephan.



# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
export PATH=/bin/lscript:/bin/lscript:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
